'use strict';
/* Visible public page extraction. No logins, CAPTCHA solving, hidden endpoints or evasion. */
function flattenJsonLd(value){if(Array.isArray(value))return value.flatMap(flattenJsonLd);if(!value||typeof value!=='object')return [];return [value,...(value['@graph']?flattenJsonLd(value['@graph']):[])];}
function ratingFromJsonLd(document,platform){for(const el of document.querySelectorAll('script[type="application/ld+json"]')){let nodes;try{nodes=flattenJsonLd(JSON.parse(el.textContent))}catch{continue}for(const n of nodes){const a=n.aggregateRating;if(!a||!(/bonavista/i.test(String(n.name||''))))continue;const value=Number(a.ratingValue),max=Number(a.bestRating||(platform==='Airbnb'||platform==='Google'?5:10));if(value>=0&&value<=max&&max>=5&&max<=10)return {score:value,scale:max};}}return null;}
function ratingFromPage(document,platform){
 const structured=ratingFromJsonLd(document,platform);if(structured)return structured;
 const selectors=platform==='Booking'?['[data-testid="review-score-right-component"] [data-testid="review-score-component"]','[data-testid="review-score-component"]','[data-testid="review-score-right-component"]']:platform==='Expedia'?['[data-stid="content-hotel-review-summary"]','[data-stid="property-reviews-summary"]','[data-stid="reviews-link"]']:['[data-testid="pdp-review-summary"]','[data-testid="pdp-reviews-highlight-banner-host-rating"]'];
 for(const selector of selectors){const element=document.querySelector(selector);if(!element)continue;const text=(element.getAttribute('aria-label')||'')+' '+(element.textContent||'');const match=platform==='Airbnb'?text.match(/\b([0-5][.,]\d{1,2})\b/):text.match(/\b(10(?:[.,]0)?|[0-9][.,][0-9]{1,2})\b/);if(match){const score=Number(match[1].replace(',','.'));if(score>=0&&score<=(platform==='Airbnb'?5:10))return {score};}}
 return null;
}
function categoriesFromPage(document,platform){const categoryMap={cleaning:/cleanliness|limpieza|propreté/i,staff:/staff|personal|atención|service/i,location:/location|ubicación|emplacement/i};const selectors=platform==='Booking'?['[data-testid="review-subscore"]']:platform==='Airbnb'?['[data-testid="review-subcategory-row"]']:['[data-stid="reviews-subrating"]'];const result={};for(const selector of selectors)for(const node of document.querySelectorAll(selector)){const text=(node.getAttribute('aria-label')||'')+' '+(node.textContent||'');for(const [key,re] of Object.entries(categoryMap)){if(!re.test(text))continue;const values=[...text.matchAll(/\b(10(?:[.,]0)?|[0-9][.,][0-9]{1,2})\b/g)].map(m=>Number(m[1].replace(',','.')));const value=values.find(n=>n>=0&&n<=(platform==='Airbnb'?5:10));if(value!==undefined)result[key]=value;}}return result;}
module.exports={flattenJsonLd,ratingFromJsonLd,ratingFromPage,categoriesFromPage};
