
let payload=null;const $=id=>document.getElementById(id);const euro=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n);const fmt=n=>new Intl.NumberFormat('es-ES',{maximumFractionDigits:1}).format(n);const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));

$('load').onclick=async()=>{const a=$('bookings').files[0],b=$('services').files[0];if(!a||!b){$('status').textContent='Selecciona los dos archivos de la misma exportación.';return} $('status').textContent='Validando los archivos…';$('dashboard').classList.add('hidden');try{const data=await analyseFiles(a,b);payload=data;let saved=true;let isNew=true;try{isNew=await saveSnapshot(data,a.name,b.name)}catch(err){saved=false}setupFilters(data);$('dashboard').classList.remove('hidden');$('status').textContent=(saved?(isNew?'Nueva captura guardada: ':'Captura idéntica a otra ya guardada; sin duplicar: '):'Importación mostrada sin guardar; el navegador bloqueó el almacenamiento local: ')+data.meta.reservations+' reservas y '+data.meta.service_lines+' líneas de servicios.';render()}catch(e){$('status').textContent='Error: '+e.message}};
$('building').onchange=()=>render();$('month').onchange=()=>render();
document.querySelector('.settings-link')?.addEventListener('click',e=>{e.preventDefault();$('settings').open=true;$('settings').scrollIntoView({behavior:'smooth',block:'start'})});
$('openSnapshot').onclick=async()=>{const id=$('snapshots').value;if(!id)return;const record=(await listSnapshots()).find(x=>x.id===id);if(!record)return;payload=record.data;window.PORTFOLIO_BOOKINGS=record.data.bookings;window.PORTFOLIO_ASOF=Object.fromEntries([...new Set(record.data.bookings.map(x=>x.month))].map(month=>[month,record.data.meta.as_of||id.slice(0,10)]));setupFilters(payload);$('dashboard').classList.remove('hidden');$('status').textContent='Carga del '+new Date(id).toLocaleString('es-ES')+' · '+record.bookName;render()};
$('openPortfolio').onclick=async()=>{await refreshPortfolio();if(!window.PORTFOLIO_BOOKINGS.length)return;if(!payload)payload=(await listSnapshots())[0].data;$('dashboard').classList.remove('hidden');setupFilters(payload||{bookings:window.PORTFOLIO_BOOKINGS});$('status').textContent='Acumulado: captura más reciente de cada mes guardado.';render()};
$('backup').onclick=()=>exportSnapshots().catch(e=>$('status').textContent=e.message);
$('restoreBackup').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const result=await restoreSnapshots(file);$('status').textContent=`Copia incorporada: ${result.added} cargas y ${result.marketAdded} observaciones de mercado nuevas. Los datos previos se conservan.`;if(payload){setupFilters(payload);render()}}catch(e){$('status').textContent='No se pudo recuperar la copia: '+e.message}event.target.value=''});
refreshSnapshots().catch(e=>$('status').textContent='No se puede acceder al almacenamiento local: '+e.message);
renderLastBackup();
(async()=>{try{const items=await listSnapshots();if(!items.length)return;await refreshPortfolio();if(!window.PORTFOLIO_BOOKINGS.length)return;payload=items[0].data;setupFilters(payload);$('dashboard').classList.remove('hidden');$('status').textContent='Cargado automáticamente con lo guardado en este navegador ('+items.length+' capturas). Sube un archivo solo para añadir un mes nuevo o actualizar el mes en curso.';render()}catch(e){}})();
function subset(){const p=window.periodMonths?window.periodMonths():null,months=p?new Set(p.months):null,building=$('building').value;return (window.PORTFOLIO_BOOKINGS?.length?window.PORTFOLIO_BOOKINGS:payload.bookings).filter(x=>(!building||x.building===building)&&(!months||months.has(x.month)))}
function distribution(rows,key,element,measure='gross',limit=10){const sums={};for(const r of rows)sums[r[key]]=(sums[r[key]]||0)+(measure==='count'?1:r[measure]);const entries=Object.entries(sums).sort((a,b)=>b[1]-a[1]).slice(0,limit),max=entries[0]?.[1]||1,total=rows.reduce((s,r)=>s+(measure==='count'?1:r[measure]),0)||1;$(element).innerHTML=entries.length?entries.map(([name,n])=>`<div class="barrow"><span title="${escape(name)}">${escape(name.length>22?name.slice(0,20)+'…':name)}</span><div class="track"><div class="fill" style="width:${Math.max(1,100*n/max)}%"></div></div><span class="right">${(element==='countries'||element==='channels')?fmt(n/total*100)+' %':euro(n)}</span></div>`).join(''):'<p class="note">Sin datos para el filtro seleccionado.</p>'}
function render(){const rows=subset(),n=rows.length,nights=rows.reduce((a,b)=>a+b.nights,0);$('coverage').textContent=n+' reservas · '+(nights?fmt(nights)+' noches':'sin noches');$('printMeta').textContent='Periodo: '+($('month').value||'mes más reciente')+' · Edificio: '+($('building').value||'todos')+' · Reservas: '+n+' · Elaborado: '+new Date().toLocaleDateString('es-ES');distribution(rows,'channel','channels');distribution(rows,'building','buildings');distribution(rows,'country','countries','count');distribution(rows,'rate','rates');distribution(rows,'roomType','roomtypes');$('quality').textContent=`Datos de origen: ${payload.meta.channel_coverage}/${payload.meta.reservations} reservas con canal; ${payload.meta.excluded_reservations||0} reservas no confirmadas excluidas; ${payload.meta.date_warnings} diferencias entre fechas y noches; ${payload.meta.reconciliation_warnings} reservas cuyo total PVP no coincide con los conceptos del CSV menos el descuento registrado. Consultar a Pablo cualquier diferencia restante. La producción está agrupada provisionalmente por mes de llegada.`;$('detail').classList.add('hidden')}
function detail(key){const rows=subset(),months=[...new Set(rows.map(x=>x.month))].sort();const labels={gross:'Producción PVP',count:'Reservas',nights:'Noches reservadas',stay:'Estancia media',guests:'Ocupantes medios',lead:'Antelación media'};let html='<h2>'+labels[key]+' · evolución por mes de llegada</h2>';for(const m of months){const group=rows.filter(x=>x.month===m),n=group.length,total=k=>group.reduce((s,x)=>s+x[k],0),known=group.filter(x=>x.guests!==null);let v={gross:euro(total('gross')),count:fmt(n),nights:fmt(total('nights')),stay:fmt(total('nights')/n)+' noches',guests:known.length?fmt(known.reduce((s,x)=>s+x.guests,0)/known.length):'—',lead:fmt(total('lead')/n)+' días'}[key];html+=`<div class="barrow"><span>${escape(m)}</span><span></span><b class="right">${v}</b></div>`}html+='<p class="note">Periodo atribuido a la llegada. La comparación interanual se habilitará al importar los periodos correspondientes.</p>';html+='<h3>Reservas del filtro ('+rows.length+')</h3><div style="max-height:360px;overflow:auto"><table style="width:100%;border-collapse:collapse;font-size:12px"><thead><tr><th>ID</th><th>Mes</th><th>Edificio</th><th>Canal</th><th>Noches</th><th>Producción</th><th>Descuento</th></tr></thead><tbody>'+rows.map(x=>`<tr><td>${escape(x.id)}</td><td>${escape(x.month)}</td><td>${escape(x.building)}</td><td>${escape(x.channel)}</td><td>${fmt(x.nights)}</td><td>${euro(x.gross)}</td><td>${euro(x.discount||0)}</td></tr>`).join('')+'</tbody></table></div>'; $('detail').innerHTML=html;$('detail').classList.remove('hidden');$('detail').scrollIntoView({behavior:'smooth',block:'nearest'})}

function setupFilters(data){const options=(id,key,label)=>{const values=[...new Set((window.PORTFOLIO_BOOKINGS?.length?window.PORTFOLIO_BOOKINGS:data.bookings).map(x=>x[key]))].sort();$(id).innerHTML='<option value="">'+label+'</option>'+values.map(x=>`<option value="${escape(x)}">${escape(x)}</option>`).join('')};options('building','building','Todos los edificios');options('month','month','Mes más reciente')}
