/* Market observations: no reservation data leaves the browser. */
(function(){
'use strict';
const KEY='bonavista-market-v1', REVIEW_KEY='bonavista-reviews-v1';
const $m=id=>document.getElementById(id);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'{"reviews":[],"rates":[]}')}catch{return {reviews:[],rates:[]}}}
function validateDate(value){if(typeof value!=='string'||!/^\d{4}-\d\d-\d\d(?:T.*)?$/.test(value)||!Number.isFinite(Date.parse(value)))throw Error('Fecha inválida: '+value);return value}
function validate(body){if(!body||body.format!=='bonavista-market-v1'||!Array.isArray(body.reviews)||!Array.isArray(body.rates))throw Error('Formato de integración inválido');if(body.reviews.length>5000||body.rates.length>10000)throw Error('Demasiados registros');return body}
function ingest(body){validate(body);const db=read(),reviews=JSON.parse(localStorage.getItem(REVIEW_KEY)||'{}');let addedReviews=0,addedRates=0;
 for(const r of body.reviews){if(!['Booking','Expedia','Airbnb','Google'].includes(r.platform)||typeof r.building!=='string'||!r.building.trim()||!Number.isFinite(r.score)||r.score<0||r.score>(['Booking','Expedia'].includes(r.platform)?10:5))throw Error('Valoración inválida');validateDate(r.capturedAt);if(typeof r.source!=='string'||!/^https:\/\//.test(r.source))throw Error('Fuente de valoración inválida');const id=[r.platform,r.building,r.source].join('|');const series=db.reviews.filter(x=>[x.platform,x.building,x.source].join('|')===id).sort((a,b)=>a.capturedAt.localeCompare(b.capturedAt));const last=series.at(-1);const categories=r.categories&&typeof r.categories==='object'?r.categories:{};if(last&&last.score===r.score&&JSON.stringify(last.categories||{})===JSON.stringify(categories))continue;const record={platform:r.platform,building:r.building,capturedAt:r.capturedAt,score:r.score,categories,source:r.source};db.reviews.push(record);(reviews[r.building+'|'+r.platform]??=[]).push({date:r.capturedAt,score:r.score,categories,source:r.source});addedReviews++}
 for(const r of body.rates){if(typeof r.property!=='string'||!r.property.trim()||typeof r.building!=='string'||!r.building.trim()||typeof r.source!=='string'||!/^https:\/\//.test(r.source)||!Number.isFinite(r.total)||r.total<0||!Number.isInteger(r.guests)||r.guests<1||!Number.isInteger(r.nights)||r.nights<1||r.nights>60||typeof r.currency!=='string'||!/^[A-Z]{3}$/.test(r.currency))throw Error('Tarifa inválida');validateDate(r.capturedAt);validateDate(r.checkin);const key=x=>[x.property,x.building,x.source,x.checkin,x.nights,x.guests,x.currency,x.total,x.plan||''].join('|');if(db.rates.some(x=>key(x)===key(r)))continue;db.rates.push({property:r.property,building:r.building,source:r.source,capturedAt:r.capturedAt,checkin:r.checkin,nights:r.nights,guests:r.guests,currency:r.currency,total:r.total,plan:r.plan||''});addedRates++}
 localStorage.setItem(KEY,JSON.stringify(db));localStorage.setItem(REVIEW_KEY,JSON.stringify(reviews));if(typeof showReviews==='function'&&$m('dashboard')&&!$m('dashboard').classList.contains('hidden'))showReviews();renderMarket();return {addedReviews,addedRates}}
function renderMarket(){const db=read(),building=$m('building')?.value||'',filtered=db.rates.filter(x=>!building||x.building===building),latest=[...filtered].sort((a,b)=>b.capturedAt.localeCompare(a.capturedAt)).slice(0,12);$m('marketTable').innerHTML=latest.length?'<div class="market-scroll"><table class="detail-table"><thead><tr><th>Alojamiento</th><th>Fecha estancia</th><th>Noches / personas</th><th>Precio total</th><th>Capturado</th><th>Fuente</th></tr></thead><tbody>'+latest.map(x=>`<tr><td>${escape(x.property)}<small> · ${escape(x.building)}</small></td><td>${escape(x.checkin.slice(0,10))}</td><td>${x.nights} / ${x.guests}</td><td>${new Intl.NumberFormat('es-ES',{style:'currency',currency:x.currency}).format(x.total)}</td><td>${escape(x.capturedAt.slice(0,10))}</td><td><a href="${escape(x.source)}" target="_blank" rel="noopener noreferrer">Abrir</a></td></tr>`).join('')+'</tbody></table></div>':'<p class="note">No hay tarifas verificadas para este edificio. Se mostrarán aquí al conectar una fuente autorizada.</p>';$m('marketCount').textContent=db.reviews.length+' cambios de valoración · '+db.rates.length+' precios distintos guardados';}
async function refresh(){const button=$m('marketRefresh'),endpoint=window.BONAVISTA_MARKET_ENDPOINT;if(!endpoint){$m('marketStatus').textContent='La actualización automática se activará cuando esté conectado el servicio de mercado.';return}button.disabled=true;$m('marketStatus').textContent='Consultando mercado…';try{const response=await fetch(endpoint,{method:'POST',headers:{'Accept':'application/json'},credentials:'same-origin',cache:'no-store'});if(!response.ok)throw Error('El servicio de mercado devolvió HTTP '+response.status);const content=await response.json(),result=ingest(content);$m('marketStatus').textContent=`Actualizado: ${result.addedReviews} cambios de nota y ${result.addedRates} precios nuevos. ${content.errors?.length||0} fichas no disponibles${content.errors?.length?': '+content.errors.map(x=>x.platform+' / '+x.building+' ('+x.error+')').join('; '):''}. Los valores repetidos no se guardan.`}catch(error){$m('marketStatus').textContent=error instanceof TypeError?'El servicio de mercado no responde. Inténtalo más tarde.':error.message}finally{button.disabled=false}}
$m('marketRefresh').addEventListener('click',refresh);$m('marketFile').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{const result=ingest(JSON.parse(await file.text()));$m('marketStatus').textContent=`Importación: ${result.addedReviews} cambios de nota y ${result.addedRates} precios nuevos.`}catch(error){$m('marketStatus').textContent=error.message}event.target.value=''});$m('building').addEventListener('change',renderMarket);renderMarket();if(!window.BONAVISTA_MARKET_ENDPOINT){$m('marketRefresh').disabled=true;$m('marketRefresh').title='Servicio de mercado pendiente de activación'}window.BONAVISTA_MARKET={ingest,read};
})();
