const DB_NAME = 'bonavista-dashboard-v1';
function database(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>request.result.createObjectStore('snapshots',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
function snapshotFingerprint(data){return JSON.stringify([...data.bookings].sort((a,b)=>String(a.id).localeCompare(String(b.id))).map(x=>[x.id,x.arrival,x.departure,x.gross,x.discount,x.nights,x.status,x.channel,x.rate,x.building,x.apartment]))}
async function saveSnapshot(data,bookName,servicesName){const older=await listSnapshots(),fingerprint=snapshotFingerprint(data);if(older.some(x=>snapshotFingerprint(x.data)===fingerprint))return false;const db=await database(),id=new Date().toISOString();await new Promise((resolve,reject)=>{const t=db.transaction('snapshots','readwrite');t.objectStore('snapshots').put({id,bookName,servicesName,data});t.oncomplete=resolve;t.onerror=()=>reject(t.error)});db.close();await refreshSnapshots();await refreshPortfolio();return true}
async function listSnapshots(){const db=await database();const items=await new Promise((resolve,reject)=>{const q=db.transaction('snapshots').objectStore('snapshots').getAll();q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});db.close();return items.sort((a,b)=>b.id.localeCompare(a.id))}
async function refreshSnapshots(){const items=await listSnapshots();const select=document.getElementById('snapshots');select.innerHTML='<option value="">Seleccionar carga guardada</option>'+items.map(x=>`<option value="${x.id}">${new Date(x.id).toLocaleString('es-ES')} · ${x.data.meta.reservations} reservas</option>`).join('');return items}
const BACKUP_KEYS=['bonavista-market-v1','bonavista-reviews-v1','bonavista-model-v1'];
const LAST_BACKUP_KEY='bonavista-last-backup-v1';
function renderLastBackup(){const holder=document.getElementById('lastBackup');if(!holder)return;const iso=localStorage.getItem(LAST_BACKUP_KEY);const folderNote=window.BONAVISTA_FOLDER?' Además, cada cambio se guarda solo en tu carpeta conectada.':'';holder.textContent=(iso?'Última copia generada el '+new Date(iso).toLocaleString('es-ES'):'Todavía no se ha descargado ninguna copia de dashboard.')+folderNote+(window.BONAVISTA_FOLDER?'':' Este botón la descarga a tu carpeta de Descargas de Windows, no a la carpeta de Bonavista.')}
async function buildBackupPayload(){const items=await listSnapshots(),extras={};for(const key of BACKUP_KEYS){const value=localStorage.getItem(key);if(value!==null)extras[key]=JSON.parse(value)}
 const historicalData=typeof historical!=='undefined'?historical:(typeof loadHistoricalFromDb==='function'?await loadHistoricalFromDb():null);
 if(historicalData)extras['bonavista-baseline-v1']=historicalData;
 /* bonavista-market-v1/bonavista-reviews-v1 siempre tienen algo (reviews-seed.js los rellena solo
    en cada carga), así que no sirven para decidir si hay "algo que guardar": exigimos reservas o
    el histórico/modelo reales, para no generar ni sobrescribir con una copia casi vacía. */
 if(!items.length&&!extras['bonavista-baseline-v1']&&!extras['bonavista-model-v1'])throw Error('Todavía no hay datos guardados');
 const now=new Date().toISOString();return {now,json:JSON.stringify({format:'bonavista-dashboard-backup-v2',exportedAt:now,snapshots:items,extras})}}
function dashboardCopyFilename(iso){const d=new Date(iso);const pad=n=>String(n).padStart(2,'0');return 'Copia de dashboard '+d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate())+' '+pad(d.getHours())+'-'+pad(d.getMinutes())+'-'+pad(d.getSeconds())+'.bonavista'}
async function exportSnapshots(){const {now,json}=await buildBackupPayload();const blob=new Blob([json],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=dashboardCopyFilename(now);a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);localStorage.setItem(LAST_BACKUP_KEY,now);renderLastBackup();if(typeof saveVersionToFolderIfConnected==='function')await saveVersionToFolderIfConnected()}
async function restoreSnapshots(file){if(file.size>45e6)throw Error('Copia demasiado grande');return restoreBackupObject(JSON.parse(await file.text()))}
async function restoreBackupObject(backup){if(backup.format==='bonavista-baseline-v1')throw Error('Esto es un archivo de histórico, no una copia de dashboard: usa «Elegir archivo de histórico…» + «Importar» más abajo, no este botón.');if(!['bonavista-dashboard-backup-v1','bonavista-dashboard-backup-v2'].includes(backup.format)||!Array.isArray(backup.snapshots))throw Error('No es una copia del dashboard');for(const x of backup.snapshots){if(typeof x.id!=='string'||!Array.isArray(x.data?.bookings)||!x.data?.meta)throw Error('Captura dañada en la copia')}
 const db=await database();const old=await listSnapshots(),fingerprints=new Set(old.map(x=>snapshotFingerprint(x.data)));let added=0;for(const shot of backup.snapshots){const print=snapshotFingerprint(shot.data);if(fingerprints.has(print))continue;await new Promise((resolve,reject)=>{const t=db.transaction('snapshots','readwrite');t.objectStore('snapshots').put(shot);t.oncomplete=resolve;t.onerror=()=>reject(t.error)});fingerprints.add(print);added++}db.close();
 // Merge observations by stable identity. Existing history remains in place.
 const extras=backup.extras||{},currentMarket=JSON.parse(localStorage.getItem('bonavista-market-v1')||'{"reviews":[],"rates":[]}'),incoming=extras['bonavista-market-v1'];let marketAdded=0;
 if(incoming){for(const type of ['reviews','rates']){if(!Array.isArray(incoming[type]))throw Error('Histórico de mercado dañado');const seen=new Set(currentMarket[type].map(x=>JSON.stringify(x)));for(const record of incoming[type]){const signature=JSON.stringify(record);if(seen.has(signature))continue;currentMarket[type].push(record);seen.add(signature);marketAdded++}}localStorage.setItem('bonavista-market-v1',JSON.stringify(currentMarket))}
 const reviewHistory=JSON.parse(localStorage.getItem('bonavista-reviews-v1')||'{}');for(const [key,series] of Object.entries(extras['bonavista-reviews-v1']||{})){if(!Array.isArray(series))continue;const existing=reviewHistory[key]||[],seen=new Set(existing.map(x=>JSON.stringify(x)));for(const value of series){const signature=JSON.stringify(value);if(!seen.has(signature)){existing.push(value);seen.add(signature)}}existing.sort((a,b)=>a.date.localeCompare(b.date));reviewHistory[key]=existing}localStorage.setItem('bonavista-reviews-v1',JSON.stringify(reviewHistory));
 if(extras['bonavista-model-v1']!==undefined&&!localStorage.getItem('bonavista-model-v1'))localStorage.setItem('bonavista-model-v1',JSON.stringify(extras['bonavista-model-v1']));
 let historicoAdded=0,historicoUpdated=0;
 const incomingBaseline=extras['bonavista-baseline-v1'];
 if(incomingBaseline&&Array.isArray(incomingBaseline.rows)&&typeof mergeHistorico==='function'){const {merged,added,updated}=mergeHistorico(typeof historical!=='undefined'?historical:null,incomingBaseline);await saveHistoricalToDb(merged);if(typeof historical!=='undefined')historical=merged;historicoAdded=added;historicoUpdated=updated}
 await refreshSnapshots();await refreshPortfolio();if(typeof renderMarket==='function')renderMarket();return {added,marketAdded,historicoAdded,historicoUpdated}}
